### ISSUE TITLE
Choix de la langue pour le code et la documentation

### ISSUE THREAD

**Issue by ldez** [swcraftlyon/meetup#2]
Votez pour votre choix :
https://framadate.org/HLERNYj4gipyUrWy

**Comment by fpellet** [comment]
Pour moi, le problème n'est pas forcement dans la langue, mais dans le vocabulaire utilisé
Si on utilise le même partout, cela me va.
Par exemple si on choisi Activity, il faut alors le mot Activity dans le code et la doc, quelque soit la langue.

**Comment by ldez** [comment]
Pour débattre plus directement, go on : https://lyontechhub.slack.com/messages/swcrafts_meetup

**Comment by devcrafting** [comment]
Les différents arguments discutés sur Slack :
- tout le monde ne maitrise pas bien l'anglais => clivant de limiter à l'anglais, risque de limiter les participations
- on pourrait partager ce qu'on fait avec d'autres personnes (lors de Socrates par exemple...) et s'il y a du français ce sera un frein => certes ce n'est pas l'objectif premier de tous
- avoir de la doc (qui va notamment exprimer l'Ubiquituous language) en français et le code en Anglais (qui reprend aussi l'Ubiquituous Language), il va y avoir du Franglish un peu partout, c'est assez indigeste je trouve
- faire tout en anglais c'est aussi une occasion de s'améliorer (je ne serais pas du tout contre des commentaires sur la langue dans les PR...l'expressivité fait partie du Clean Code...)
- écrire et lire du code en anglais est beaucoup plus simple que d'écrire et lire des phrases de documentation en anglais => /!\ à ne pas considérer qu'on peut se permettre d'être moins clair dans le code que dans la doc

**Comment by ldez** [comment]
- Je pense que faire la doc est anglais est clivant : tout le monde ne maitrise pas bien l'anglais.
- le partage avec l'extérieur n'est pas une priorité de ce projet.
- pour éliminer les problèmes de vocabulaire, il faudrait simplement faire un glossaire.
- écrire et lire du code en anglais est beaucoup plus simple que d'écrire et lire des phrases de documentation en anglais.
- penser que ce sera le lieu pour améliorer son anglais est aussi clivant.
- Je n'aimerais pas que cela soit limitant pour la participation au projet.

**Comment by mbaechler** [comment]
I do think that sharing (whatever the scope) is a priority.

I also think that a Crafts(wo)man can't be a good programmer if (s)he is not able to express its intent in a decent english in its code. So why would (s)he refuse to write in a decent english in its documentation ? I don't even understand what you mean by documentation : for me, the code, the tests, etc, is documentation, don't you think ?
