### ISSUE TITLE
What is the difference between an Event and an Activity?

### ISSUE THREAD

**Issue by bravogolfgolf** [swcraftlyon/meetup#20]
This is from the README:

> Activities : what people have to propose for an event, can be a talk, a workshop, a run, a game...
> Events : organize an event that will propose activities and that people can join to share this activity...
- Is an Event a collection of Activities? Like a conference with many talks.
- Is an Activity just a type of Event? A talk Event, a workshop Event, etc.
- Is Event a suggestion generater? If you liked that running Activity you might likes these other running Activities too.
- Are the two actually the same thing?

**Comment by thebignet** [comment]
I guess (I'll let others correct me if I'm wrong) that an Event is is a talk/workshop/run/game that will happen or has happened, while an activity is more generic, does'nt have a fixed date and can happen several times.  For example if a group of people like to play tennis, tennis would be the activity while "this saturday afternoon tennis at the park" would be the event.

This means that people can suggest activities they would like to happen.  Someone can then make an event out of an activity.

**Comment by bravogolfgolf** [comment]
> I guess (I'll let others correct me if I'm wrong) that an Event is is a talk/workshop/run/game that will happen or has happened,

I agree.

> while an activity is more generic, does'nt have a fixed date and can happen several times.

However, this sounds a lot like an Event too. An Event without a fixed date is a suggestion. An Event that happens several times is a recurring Event.

> For example if a group of people like to play tennis, tennis would be the activity

This seems to make Activity an attribute of User.

> while "this saturday afternoon tennis at the park" would be the event.

I agree.

> This means that people can suggest activities they would like to happen. Someone can then make an event out of an activity.

It would allow an Organizer (Role played by User) of an Event to find a potential Participant and/or Presenter (Roles played by User) based on their Activity (or other attibutes, where they live for instance) and message them.

**Comment by bravogolfgolf** [comment]
I went back to the Event Storming pictures and the Activity does not seem to be in any of the photos...it seems to have entered the when cards were added to the Trello board. On the Trello board there is a lot of overlap with cards related to Event and Activity. I believe they are the same thing and we just need to settle on the word we want to use...and then update Trello, the README and our directory structure.

**Comment by thebignet** [comment]
I think that distinction occured at the 3rd meeting, when categories changed.  Since I wasn't there, maybe someone else could explain exactly what the difference is ?

**Comment by Dayde** [comment]
While we were adding the trello cards we split into 3 groups : spectators, organizers, speakers.

Spectators can attend an event.
Event are organized by organizers.
Organizers pick in a pool of talks suggested by speakers.

At first we called it talks and speakers but we thought, why restrain this to only talks ? What if we want another kind of activity ?

That's why we ended up with :
Organizers pick in a pool of activities suggested by other people.

**Comment by bravogolfgolf** [comment]
@Dayde @thebignet Thank you for your feedback.

> Spectators can attend an event.

Agree. However, I would suggest Participant rather than Spectator to describe this Role.
User (Participant) attends an Event.

> Event are organized by organizers.

No arguement here either. I think Organizer is a good name for the Role too.
User (Organizer) creates an Event.

> At first we called it talks and speakers but we thought, why restrain this to only talks ? What if we want another kind of activity ?
> 
> That's why we ended up with :
> Organizers pick in a pool of activities suggested by other people.

I also agree that generalizing talks to something else is a good idea. I would suggest Interest rather than Activity.

Now to the part that needs clarification...

> Organizers pick in a pool of activities suggested by other people.

This is search functionality.

For example, An User (Organizer) wants to create an Event based on an Interest and they need to find a User (Presenter) who knows the Interest to lead other Users (Participants) with the same Interest.

The same applies to an User (Organizer) who wants to create an Event based on an Interest, but who does not need a User (Presenter). The User (Organizer) still needs to find other Users (Participants) with the same Interest.

It also applies to an User (Participant) who wants to find an Event based on an Interest.

To me Organizer, Presenter and Participant are all Roles played by an User on a Event. The thing that all these Users and Event share is an Interest.

I opened an another issue to capture changes to the domain model based on the information from this discussion and potentially other discussions as they provide deeper insight and evole the domain model.
