### ISSUE TITLE
What is the process/criteria for accepting a pull request?

### ISSUE THREAD

**Issue by bravogolfgolf** [swcraftlyon/meetup#21]
Right now it seems like we are looking for consensus...if we get enough LGTMs then we move forward. That seems good enough and I am not proposing changing it.

But on certain issues I do not have the knowledge or experience to respond with LGTM. How should I indicate that I have no opinion so you are not endlessly waiting for my confirmation that will never come?

For now I am going to use: ITYO (I Trust Your Opinion).

**Comment by ldez** [comment]
LGTM

**Comment by thebignet** [comment]
Github have recently added reactions to comments (the smiley faced icon on each comment).  Therefore it should be relatively concise and simple to vote on the issue.  Instead of LGTM or ITYO, we can use :+1: or :confused: or even :-1:  (or whichever else suits actually).

**Comment by bravogolfgolf** [comment]
I would agree with you if we could add these reactions on the pull request or issue itself.

However, these reactions are on comments...I see situations where I am LGTM or ITYO on an issue and :+1: , :confused: or :-1: on a comment. I also see situations where I may start off on an issue as LGTM, but then -- based on subsequent comments and direction -- change my opinion. Having that change of opinion documented in-line -- rather than on an unrelated comment earlier in the thread -- has value.

**Comment by thebignet** [comment]
I guess we could use the reaction on the very first comment of a pull request which is the description of the pull request.  It would be nice to change a reaction to update the PR accordingly.
