### ISSUE TITLE
Choix du/des languages

### ISSUE THREAD

**Issue by ldez** [swcraftlyon/meetup#3]
Je place ici les liens des précédents sondages pour mémoire :
- Sondage Backend : https://framadate.org/CwuaEKFUM7AxIgxBetynXD1R/admin
- Sondage Frontend : https://framadate.org/EKqFmFldEulEtOB8QFJwTpfJ/admin

**Comment by nicolaspayot** [comment]
Je crois que pour le front c'est assez clair (même si ici on parle de framework et pas de langage)

**Comment by ldez** [comment]
Pour débattre go on : https://lyontechhub.slack.com/messages/swcrafts_meetup
