### ISSUE TITLE
Format des messages des commits

### ISSUE THREAD

**Issue by nicolaspayot** [swcraftlyon/meetup#4]
Je propose de suivre ce modèle pour le format des messages des commits : http://karma-runner.github.io/0.13/dev/git-commit-msg.html. Pas forcément de `<body> <footer>` mais au moins `<type>(<scope>): <message>` avec la liste proposée pour les types sur la doc : 
- **feat** (new feature for the user, not a new feature for build script)
- **fix** (bug fix for the user, not a fix to a build script)
- **docs** (changes to the documentation)
- **style** (formatting, missing semi colons, etc; no production code change)
- **refactor** (refactoring production code, eg. renaming a variable)
- **test** (adding missing tests, refactoring tests; no production code change)
- **chore** (updating grunt tasks etc; no production code change)

**Comment by ldez** [comment]
Pour débattre go on : https://lyontechhub.slack.com/messages/swcrafts_meetup

**Comment by mbaechler** [comment]
I usually prefix my commits by the related issue, so type and scope are useless in the case.
Do we plan to work based on issue ? If not, this format looks ok to me.

**Comment by ldez** [comment]
En fait le format proposé par @nicolaspayot marche aussi avec les issues.

Voici un exemple :

```
feat(event): add new event

Add event when foo..?

closes #123
```

Ce format l'integre avec GitHub, quand il voit le mot `closes` suivie d'un numéro d'issue il ferme automatiquement l'issue lors du merge.

https://github.com/blog/831-issues-2-0-the-next-generation

**Comment by CharlesBouttaz** [comment]
LGTM

**Comment by bravogolfgolf** [comment]
LGTM
